name = "JLD2DebugTools"
uuid = "dea85e0d-6592-4e00-a4c6-932bfb2a034d"
authors = ["Jonas Isensee <jonas.isensee@web.de> and contributors"]
version = "0.1.1"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.5"
Reexport = "1"
JLD2 = "0.5"
